Use maven exec plugin rather than jlink and jpackage plugins.

diff --git a/converter.app/src/main/jpackage-data/linuxOverride/postrm b/converter.app/src/main/jpackage-data/linuxOverride/postrm
--- a/converter.app/src/main/jpackage-data/linuxOverride/postrm
+++ b/converter.app/src/main/jpackage-data/linuxOverride/postrm
@@ -2,37 +2,34 @@
 # postrm script for jpdfbookmarks
 #
 # see: dh_installdeb(1)
+
 set -e
+
 # summary of how this script can be called:
-#
-* <postrm> `remove'
-#
-* <postrm> `purge'
-#
-* <old-postrm> `upgrade' <new-version>
-#
-* <new-postrm> `failed-upgrade' <old-version>
-#
-* <new-postrm> `abort-install'
-#
-* <new-postrm> `abort-install' <old-version>
-#
-* <new-postrm> `abort-upgrade' <old-version>
-#
-* <disappearer's-postrm> `disappear' <overwriter>
-#
-<overwriter-version>
+#        * <postrm> `remove'
+#        * <postrm> `purge'
+#        * <old-postrm> `upgrade' <new-version>
+#        * <new-postrm> `failed-upgrade' <old-version>
+#        * <new-postrm> `abort-install'
+#        * <new-postrm> `abort-install' <old-version>
+#        * <new-postrm> `abort-upgrade' <old-version>
+#        * <disappearer's-postrm> `disappear' <overwriter>
+#          <overwriter-version>
 # for details, see https://www.debian.org/doc/debian-policy/ or
 # the debian-policy package
+
 case "$1" in
-	purge|remove)
-		update-alternatives --remove converter /usr/bin/converter || true
-	;;
-	upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
-	;;
-	*)
-		echo "postrm called with unknown argument \`$1'" >&2
-		exit 1
-	;;
+    purge|remove)
+           update-alternatives --remove converter /usr/bin/converter || true 
+    ;;
+    
+    upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
+    ;;
+
+    *)
+        echo "postrm called with unknown argument \`$1'" >&2
+        exit 1
+    ;;
 esac
+
 exit 0
